name: Linux CMake Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Vulkan SDK
      run: |
        wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-noble.list http://packages.lunarg.com/vulkan/lunarg-vulkan-noble.list
        sudo apt update
        sudo apt install -y vulkan-sdk
    
    - name: Install SDL2 and dependencies
      run: |
        sudo apt install -y libsdl2-2.0-0 libsdl2-dev libsdl-image1.2-dev libsdl1.2-dev

    - name: Create build directory and run CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make -j$(nproc)

    - name: List build directory contents
      run: |
        ls -l ./tests

    - name: Upload RendererTests binary
      uses: actions/upload-artifact@v4
      with:
        name: renderer-tests
        path: build/RendererTests 
  
  test-linux:
    needs: build-linux
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download RendererTests artifact
      uses: actions/download-artifact@v4
      with:
        name: renderer-tests
        path: ./tests

    - name: Run RendererTests
      run: |
        chmod +x ./tests/RendererTests
        ./tests/RendererTests