name: Style Check

on:
  pull_request:
    branches: [ main ]

jobs:
  clang-format-check:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install clang-format
      run: |
        sudo apt update
        sudo apt install -y clang-format

    - name: Check clang-format
      run: |
        find VkRenderer/ tests/ -name "*.cpp" -o -name "*.h" -o -name "*.hpp" | xargs clang-format --dry-run --Werror