name: Style Checks

on: 
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  clang-format-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run clang-format lint
      uses: DoozyX/clang-format-lint-action@v0.20
      with:
        source: '.'
        exclude: './third_party ./external'
        extensions: 'h,cpp'
        clangFormatVersion: 20
        style: LLVM
        inplace: false